spring.application.name=foodcode

# MongoDB Configuration
spring.data.mongodb.database=test
spring.data.mongodb.uri=mongodb://localhost:27017/test

# Server Port
server.port=8080

# File Upload Configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB